# Generated by Django 4.2.4 on 2023-08-25 14:12

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial')], default='select', max_length=100)),
                ('property_for', models.CharField(choices=[('Buyer', 'Buyer'), ('Renter', 'Renter')], default='select', max_length=20)),
                ('flat_number', models.CharField(blank=True, max_length=5)),
                ('bedrooms', models.CharField(blank=True, max_length=5)),
                ('bathrooms', models.CharField(blank=True, max_length=5)),
                ('living_rooms', models.CharField(blank=True, max_length=5)),
                ('kitchens', models.CharField(blank=True, max_length=5)),
                ('total_rooms', models.CharField(blank=True, max_length=5)),
                ('parking', models.CharField(blank=True, max_length=15)),
                ('built_year', models.CharField(blank=True, max_length=5)),
                ('built_area', models.CharField(blank=True, max_length=20)),
                ('road_size', models.CharField(blank=True, max_length=20)),
                ('land_area', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('facing_direction', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('price_per_unit', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=20)),
                ('ward_no', models.CharField(blank=True, max_length=5)),
                ('tole', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('Select', 'Select'), ('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold')], default='', max_length=20)),
                ('featured', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Select', max_length=3)),
                ('image', models.ImageField(blank=True, upload_to=app.models.image_validations)),
                ('image_side', models.ImageField(blank=True, upload_to=app.models.image_validations)),
                ('image_extra', models.ImageField(blank=True, upload_to=app.models.image_validations)),
                ('image_extra2', models.ImageField(blank=True, upload_to=app.models.image_validations)),
            ],
        ),
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Commercial Property', 'Commercial Property')], default='select', max_length=30)),
                ('property_for', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='select', max_length=25)),
                ('flat_number', models.CharField(blank=True, max_length=5)),
                ('bedrooms', models.CharField(blank=True, max_length=5)),
                ('bathrooms', models.CharField(blank=True, max_length=5)),
                ('living_rooms', models.CharField(blank=True, max_length=5)),
                ('kitchens', models.CharField(blank=True, max_length=5)),
                ('total_rooms', models.CharField(blank=True, max_length=5)),
                ('parking', models.CharField(blank=True, max_length=15)),
                ('built_year', models.CharField(blank=True, max_length=5)),
                ('built_area', models.CharField(blank=True, max_length=20)),
                ('road_size', models.CharField(blank=True, max_length=20)),
                ('land_area', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('facing_direction', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('price_per_unit', models.CharField(blank=True, max_length=15)),
                ('full_description', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=20)),
                ('ward_no', models.CharField(blank=True, max_length=5)),
                ('tole', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('doc_image', models.ImageField(blank=True, upload_to='Sell_Request/Uploads/documents')),
                ('image_front', models.ImageField(blank=True, upload_to='Sell_Request/Uploads')),
                ('image_side', models.ImageField(blank=True, upload_to='Sell_Request/Uploads')),
                ('image_extra', models.ImageField(blank=True, upload_to='Sell_Request/Uploads')),
                ('image_extra2', models.ImageField(blank=True, upload_to='Sell_Request/Uploads')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.property')),
            ],
        ),
    ]
