# Generated by Django 4.1.7 on 2023-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('land', 'Land')], default='select', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold')], default='available', max_length=20)),
            ],
        ),
    ]
