# Generated by Django 4.1.7 on 2023-04-27 16:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Province',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.image_validations),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment')], default='select', max_length=100),
        ),
    ]
