# Generated by Django 4.2.4 on 2023-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
