# Generated by Django 4.1.7 on 2023-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_address_property_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
