# Generated by Django 4.2.4 on 2023-08-27 13:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_property_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to=app.models.image_validations),
        ),
    ]
