# Generated by Django 4.1.7 on 2023-05-03 11:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment'), ('flat', 'Flat'), ('Office', 'office')], default='select', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=app.models.image_validations)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='available', max_length=20)),
            ],
        ),
    ]
