# Generated by Django 4.2.4 on 2023-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
