# Generated by Django 4.2.4 on 2023-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sellrequest_city_sellrequest_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrequest',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial')], default='select', max_length=30),
        ),
    ]
