# Generated by Django 4.1.7 on 2023-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('tenant', 'Tenant')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial')], default='select', max_length=100),
        ),
    ]
