# Generated by Django 4.2.4 on 2023-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sellrequest_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
