# Generated by Django 4.1.7 on 2023-05-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_property_property_for_alter_property_property_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentProperty',
        ),
        migrations.AddField(
            model_name='customermessage',
            name='property',
            field=models.ForeignKey(default='SET_DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='app.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('renter', 'Renter')], default='select', max_length=20),
        ),
    ]
