# Generated by Django 4.1.7 on 2023-05-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_rentproperty_customermessage_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='property',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.property'),
        ),
    ]
