# Generated by Django 4.1.7 on 2023-05-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customermessage_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermessage',
            name='property',
        ),
    ]
