# Generated by Django 4.2.1 on 2023-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Renter', 'Renter')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Select', 'Select'), ('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold')], default='Select', max_length=20),
        ),
    ]
