# Generated by Django 4.2.1 on 2023-05-26 06:15

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sellrequests_alter_customermessage_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to='property_images', validators=[app.validators.image_validations]),
        ),
    ]
