# Generated by Django 4.1.7 on 2023-05-27 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=15)),
                ('property_for', models.CharField(max_length=10)),
                ('flat_number', models.IntegerField(blank=True)),
                ('bedrooms', models.IntegerField(blank=True)),
                ('bathrooms', models.IntegerField(blank=True)),
                ('living_rooms', models.IntegerField(blank=True)),
                ('kitchens', models.IntegerField(blank=True)),
                ('total_rooms', models.IntegerField(blank=True)),
                ('parking', models.CharField(blank=True, max_length=15)),
                ('built_year', models.IntegerField(blank=True)),
                ('built_area', models.CharField(blank=True, max_length=20)),
                ('road_size', models.CharField(blank=True, max_length=20)),
                ('land_area', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('facing_direction', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('price_per_unit', models.CharField(blank=True, max_length=15)),
                ('full_description', models.TextField(blank=True, max_length=300)),
                ('province', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=20)),
                ('ward_no', models.CharField(blank=True, max_length=5)),
                ('tole', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('image', models.ImageField(blank=True, upload_to='Sell_Requests')),
            ],
        ),
        migrations.DeleteModel(
            name='SellRequests',
        ),
    ]
