# Generated by Django 4.2.1 on 2023-05-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_sellrequest_delete_sellrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrequest',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='flat_number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='image',
            field=models.ImageField(blank=True, upload_to='Sell_Requests/'),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='kitchens',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='living_rooms',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='property_for',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='select', max_length=25),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='property_title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Commercial Property', 'Commercial Property')], default='select', max_length=30),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='total_rooms',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
