# Generated by Django 4.2.1 on 2023-05-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_sellrequest_bathrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='path/to/upload/folder')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='image',
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='images',
            field=models.ManyToManyField(to='app.uploadedimage'),
        ),
    ]
