# Generated by Django 4.2.1 on 2023-05-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_uploadedimage_remove_sellrequest_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='Sell_Request/Uploads/'),
        ),
    ]
