# Generated by Django 4.2.1 on 2023-05-29 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_sellrequest_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=15)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Commercial Property', 'Commercial Property')], default='select', max_length=30)),
                ('property_for', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='select', max_length=25)),
                ('flat_number', models.CharField(blank=True, max_length=5)),
                ('bedrooms', models.CharField(blank=True, max_length=5)),
                ('bathrooms', models.CharField(blank=True, max_length=5)),
                ('living_rooms', models.CharField(blank=True, max_length=5)),
                ('kitchens', models.CharField(blank=True, max_length=5)),
                ('total_rooms', models.CharField(blank=True, max_length=5)),
                ('parking', models.CharField(blank=True, max_length=15)),
                ('built_year', models.IntegerField(blank=True)),
                ('built_area', models.CharField(blank=True, max_length=20)),
                ('road_size', models.CharField(blank=True, max_length=20)),
                ('land_area', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('facing_direction', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('price_per_unit', models.CharField(blank=True, max_length=15)),
                ('full_description', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=20)),
                ('ward_no', models.CharField(blank=True, max_length=5)),
                ('tole', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Sell_Request/Uploads/')),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.sellrequest')),
            ],
        ),
    ]
