# Generated by Django 4.2.1 on 2023-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sellrequest_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrequest',
            name='built_year',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
