# Generated by Django 4.2.1 on 2023-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_sellrequest_built_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='doc_image',
            field=models.ImageField(blank=True, upload_to='Sell_Request/Uploads/documents'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='image_back',
            field=models.ImageField(blank=True, upload_to='Sell_Request/Uploads'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='image_extra',
            field=models.ImageField(blank=True, upload_to='Sell_Request/Uploads'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='image_extra1',
            field=models.ImageField(blank=True, upload_to='Sell_Request/Uploads'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='image_front',
            field=models.ImageField(blank=True, upload_to='Sell_Request/Uploads'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='image_right',
            field=models.ImageField(blank=True, upload_to='Sell_Request/Uploads'),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='property_title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
