# Generated by Django 4.2.1 on 2023-05-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_sellrequest_doc_image_sellrequest_image_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellrequest',
            old_name='image_back',
            new_name='image_extra2',
        ),
        migrations.RenameField(
            model_name='sellrequest',
            old_name='image_extra1',
            new_name='image_side',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='image_right',
        ),
    ]
