# Generated by Django 4.2.1 on 2023-05-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_image_back_sellrequest_image_extra2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to='property_images'),
        ),
    ]
