# Generated by Django 4.2.1 on 2023-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Select', max_length=2),
        ),
    ]
