# Generated by Django 4.2.1 on 2023-06-08 05:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_property_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='built_area',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='built_year',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='facing_direction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='flat_number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='image_extra',
            field=models.ImageField(blank=True, upload_to=app.models.image_validations),
        ),
        migrations.AddField(
            model_name='property',
            name='image_extra2',
            field=models.ImageField(blank=True, upload_to=app.models.image_validations),
        ),
        migrations.AddField(
            model_name='property',
            name='image_side',
            field=models.ImageField(blank=True, upload_to=app.models.image_validations),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchens',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='living_rooms',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='municipality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_unit',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='road_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='tole',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rooms',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='ward_no',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Select', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Select', 'Select'), ('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold')], default='', max_length=20),
        ),
    ]
